[build]
  command = "pnpm build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--version"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@aws-sdk/*"]

# 👇 Add this section to ignore secrets scan for specific keys
[secrets]
  omit_keys = [
    "AWS_ACCESS_KEY",
    "AWS_SECRET_KEY",
    "AWS_ACCESS_KEY_ID",
    "AWS_SECRET_ACCESS_KEY",
    "AWS_REGION",
    "AWS_S3_BUCKET",
    "EB_AWS_ACCESS_KEY_ID",
    "EB_AWS_SECRET_ACCESS_KEY",
    "EB_AWS_REGION",
    "EB_S3_BUCKET",
    "CLERK_SECRET_KEY",
    "MY_AWS_REGION",
    "NEXT_PUBLIC_ADMIN_PASSWORD",
    "NEXT_PUBLIC_ADMIN_USERNAME",
    "NEXT_PUBLIC_API_URL",
    "EB_API_ORIGIN",
    "NEXT_PUBLIC_*",
    "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY",
    "NEXT_PUBLIC_USER_PASSWORD",
    "NEXT_PUBLIC_USER_USERNAME",
    "S3_BUCKET_NAME"
  ]
